services:
  web:
    image: ghcr.io/postalserver/postal:${VERSION}
    command: postal web-server
    ports:
      - "5000:5000"
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  smtp:
    image: ghcr.io/postalserver/postal:${VERSION}
    command: postal smtp-server
    ports:
      - "25:25"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  worker:
    image: ghcr.io/postalserver/postal:${VERSION}
    command: postal worker
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:${VERSION}
    command: postal
    volumes:
      - /opt/postal/config:/config
    restart: unless-stopped
